Repository nestjs-shopify/nestjs-shopify, pull requests merged in 2023-04, with the labels that each got.

#166 feat: update redirect path
  .changeset/tame-ducks-eat.md
  packages/auth/src/auth.filter.ts
Labels: enhancement

#169 chore(node): upgrade to v18.15
  .github/workflows/release.yaml
  .github/workflows/tests.yaml
  .node-version
Labels: dependencies

#171 refactor(auth): simplify the controller path override provider
  .changeset/perfect-owls-jump.md
  packages/auth/src/auth.constants.ts
  packages/auth/src/auth.module.ts
  packages/auth/src/utils/build-controller-hack-for-token.util.ts
Labels: refactor

#172 fix(auth): remove constructor TS `override readonly` qualifiers
  .changeset/sour-carrots-deliver.md
  packages/auth/src/offline-auth/offline-auth.controller.ts
  packages/auth/src/online-auth/online-auth.controller.ts
Labels: refactor
